# -*- coding: utf-8 -*-
"""train_emotion_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ds2FWKR1G5O6a_duMXzKoKlTIeR77-0B
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

!cp -r /content/drive/MyDrive/AI_EXPRESSION_ANALYZER/fer_2013.csv /content/fer_data

import pandas as pd

import os

# List the contents of the 'fer_2013.csv' directory
print(os.listdir("/content/drive/MyDrive/AI_EXPRESSION_ANALYZER/fer_2013.csv"))

# Once you find the correct filename, you can update the path accordingly.
# For example, if the file is named 'actual_data.csv' inside that directory:
# data = pd.read_csv("/content/drive/MyDrive/AI_EXPRESSION_ANALYZER/fer_2013.csv/actual_data.csv")
# print(data.shape)

import os

path = "/content/drive/MyDrive/AI_EXPRESSION_ANALYZER"
print(os.listdir(path))

os.listdir("/content/drive/MyDrive/AI_EXPRESSION_ANALYZER/fer_2013.csv")

train_dir = "/content/fer_data/train"
test_dir  = "/content/fer_data/test"

import os
print(os.listdir(train_dir))

import tensorflow as tf

img_size = (48, 48)
batch_size = 128

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    image_size=img_size,
    color_mode="grayscale",
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    image_size=img_size,
    color_mode="grayscale",
    batch_size=batch_size
)

normalization_layer = tf.keras.layers.Rescaling(1./255)


train_ds = train_ds.map(lambda x, y: (normalization_layer(x), y))
val_ds   = val_ds.map(lambda x, y: (normalization_layer(x), y))

AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
val_ds   = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

from tensorflow.keras import mixed_precision
mixed_precision.set_global_policy("mixed_float16")
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
   Input, Conv2D, MaxPooling2D,
    Dense, Dropout, Flatten
)

model = Sequential([
    Input(shape=(48, 48, 1)),   # 👈 define input explicitly

    Conv2D(32, (3,3), activation="relu"),
    MaxPooling2D((2,2)),
    Dropout(0.25),

    Conv2D(64, (3,3), activation="relu"),
    MaxPooling2D((2,2)),
    Dropout(0.25),

    Conv2D(128, (3,3), activation="relu"),
    MaxPooling2D((2,2)),
    Dropout(0.25),

    Flatten(),
    Dense(128, activation="relu"),
    Dropout(0.5),

   Dense(7, activation="softmax", dtype="float32")
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

import tensorflow as tf
tf.config.list_physical_devices("GPU")

epochs = 30

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=epochs
)

model.save("emotion_cnn_model.h5")
print("Model saved successfully!")

import tensorflow as tf
print(tf.__version__)